wcs_coav_homepage:
    path:     /
    defaults: { _controller: WCSCoavBundle:Default:index }

wcs_coav_listing:
    resource: "@WCSCoavBundle/Controller/ListingController.php"
    type: annotation

wcs_coav_review:
    resource: "@WCSCoavBundle/Controller/ReviewController.php"
    type: annotation